services:


  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}_nginx
    restart: unless-stopped
    environment:
      - APP_NAME=${APP_NAME}_fpm
    volumes:
      - ../:/var/www
      - ../../${APP_NAME}-nginx_log:/var/log/nginx
    networks:
      - service_bridge
      - proxy

  fpm:
    build:
      context: ./
      dockerfile: Fpm.Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    environment:
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
    image: ${APP_NAME}_fpm
    container_name: ${APP_NAME}_fpm
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../:/var/www
    networks:
      - service_bridge

  redis:
      image: "redis:alpine"
      container_name: ${APP_NAME}_redis
      restart: unless-stopped
      ports:
          - "6379"
      volumes:
          - ../../${APP_NAME}-data/redis_data:/var/lib/postgres
      networks:
          - service_bridge
  mailpit:
    image: axllent/mailpit:latest
    container_name: ${APP_NAME}_mailpit
    restart: unless-stopped
    ports:
      - "1025"  # SMTP
      - "32786:8025"  # Web UI
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - service_bridge

networks:
  service_bridge:
    name: ${DOCKER_NETWORK_NAME}_bridge
    external: true
  proxy:
    external: true
    name: proxy
